# -*- coding: utf-8 -*-
"""password_gen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u_ozQO6xmT8UgQwy1XC2xNJivV289fXF
"""

import random
import string
import sys

def generate_password(length, use_digits, use_symbols):
    lower = string.ascii_lowercase
    upper = string.ascii_uppercase
    digits = string.digits
    symbols = string.punctuation

    char_pool = lower + upper

    if use_digits:
        char_pool += digits
    if use_symbols:
        char_pool += symbols

    if length < 4:
        print(">>> Warning: Password length increased to 4 for security.")
        length = 4

    try:
        password_list = random.choices(char_pool, k=length)
        password = "".join(password_list)
        return password
    except Exception as e:
        print(f"Error during generation: {e}")
        return None

def get_valid_integer(prompt):
    while True:
        try:
            value = input(prompt)
            if value.lower() == 'exit':
                return 'exit'
            i_val = int(value)
            if i_val <= 0:
                print(">>> Please enter a positive number.")
                continue
            return i_val
        except ValueError:
            print(">>> Invalid input. Please enter a number.")

def main():
    """
    Main loop for the application.
    """
    print("========================================")
    print("   SECURE PASSWORD GENERATOR SYSTEM     ")
    print("========================================")

    while True:
        print("\n--- New Generation Request ---")


        length = get_valid_integer("Enter password length (e.g., 12): ")
        if length == 'exit':
            break


        print("Include Numbers? (y/n): ", end="")
        digits_choice = input().strip().lower()
        use_digits = digits_choice == 'y' or digits_choice == 'yes'

        print("Include Symbols (@#$)? (y/n): ", end="")
        symbols_choice = input().strip().lower()
        use_symbols = symbols_choice == 'y' or symbols_choice == 'yes'


        print(f"\nGenerating {length}-character password...")
        pwd = generate_password(length, use_digits, use_symbols)


        if pwd:
            print("-" * 30)
            print(f"GENERATED PASSWORD:  {pwd}")
            print("-" * 30)
            print(">>> Password copied to clipboard (Simulated).")


        again = input("\nGenerate another? (yes/no): ").lower()
        if again != 'yes' and again != 'y':
            print("Exiting System. Stay Secure!")
            break

if __name__ == "__main__":
    main()